sudo: required
services:
  -docker

before_install:
  - docker build -t jekyllblog .

script:
  - docker run --volumes="$PWD:/srv/jekyll" jekyllblog rake test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master