version: '3'

services:
  jekyll:
    build:
      context: .
    container_name: jekyllblog
    environment:
      - JEKYLL_ENV=docker
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
  tests:
    build:
      context: .
    volumes:
      - .:/srv/jekyll
    command: ["rake", "test"]